In [1]:
from google.colab import files
files.upload()

Saving House_Rent_Dataset.csv to House_Rent_Dataset.csv

{'House_Rent_Dataset.csv': b'Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact\r\n2022-05-18,2,10000,1100,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-13,2,20000,800,1 out of 3,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-16,2,17000,1000,1 out of 3,Super Area,Salt Lake City Sector 2,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-07-04,2,10000,800,1 out of 2,Super Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-09,2,7500,850,1 out of 2,Carpet Area,South Dum Dum,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-04-29,2,7000,600,Ground out of 1,Super Area,Thakurpukur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-21,2,10000,700,Ground out of 4,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,2,Contact Agent\r\n2022-06-21,1,5000,250,1 out of 2,Super Area,Malancha,Kolkata,Unfurnished,Bachelors,1,Contact Agent\r\n2022-06-07,2,26000,800,1 out of 2,Carpet Area,"Palm Avenue Kolkata, Ballygunge",Kolkata,Unfurnished,Bachelors,2,Contact Agent\r\n2022-06-20,2,10000,1000,1 out of 3,Carpet Area,Natunhat,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-23,3,25000,1200,1 out of 4,Carpet Area,"Action Area 1, Rajarhat Newtown",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent\r\n2022-06-07,1,5000,400,1 out of 1,Carpet Area,Keshtopur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent\r\n2022-05-14,1,6500,250,1 out of 4,Carpet Area,"Tarulia, Keshtopur",Kolkata,Furnished,Bachelors,1,Contact Owner\r\n2022-05-09,1,5500,375,1 out of 2,Carpet Area,Dum Dum Metro,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent\r\n2022-05-05,3,8500,900,Ground out of 2,Carpet Area,Paschim Barisha,Kolkata,Unfurnished,Bachelors,2,Contact Owner\r\n2022-06-01,3,40000,1286,1 out of 1,Carpet Area,New Town Action Area 1,Kolkata,Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-17,2,6000,600,1 out of 2,Super Area,Barasat,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-20,2,10000,800,Ground out of 2,Super Area,Behala,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-09,2,11000,2000,Ground out of 3,Carpet Area,Behala Chowrasta,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-09,2,6000,660,1 out of 2,Super Area,Behala,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-07-02,2,7900,650,1 out of 2,Carpet Area,Santoshpur,Kolkata,Unfurnished,Family,1,Contact Owner\r\n2022-06-14,2,9000,400,2 out of 3,Carpet Area,"Garia Station, Garia",Kolkata,Unfurnished,Bachelors,2,Contact Owner\r\n2022-06-15,1,4000,300,Ground out of 4,Carpet Area,"Garia Station, Garia",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-15,3,6500,1600,Ground out of 2,Super Area,Joka,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-28,1,8000,400,1 out of 2,Super Area,Sreebhumi,Kolkata,Semi-Furnished,Bachelors,1,Contact Agent\r\n2022-05-22,2,7000,1000,1 out of 1,Super Area,Rajarhat,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-18,1,5300,355,1 out of 1,Carpet Area,Dum Dum,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Agent\r\n2022-06-25,2,6000,1000,Ground out of 3,Super Area,"Kodalia, Hooghly-Chinsurah",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-22,2,8500,800,4 out of 5,Super Area,Baguiati,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-25,2,12500,850,Ground out of 2,Super Area,"Rabindra Sarobar Area, Dhakuria",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-21,1,7500,350,Ground out of 2,Carpet Area,Baghajatin,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-26,2,15000,900,Ground out of 2,Carpet Area,"Project Kaikhali, Vip Road",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-16,2,6000,550,1 out of 1,Super Area,Vip Road,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-29,2,5000,500,Ground out of 2,Carpet Area,Baruipur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-10,3,22000,1100,2 out of 3,Carpet Area,Dumdum Park,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-12,2,15000,850,1 out of 2,Carpet Area,Sreebhumi,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-03,2,12500,800,2 out of 2,Carpet Area,Shyam Bazar,Kolkata,Unfurnished,Bachelors,1,Contact Agent\r\n2022-05-31,2,7000,630,Ground out of 3,Carpet Area,Birati,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-06-10,2,21000,900,1 out of 2,Carpet Area,Bansdroni,Kolkata,Semi-Furnished,Bachelors,2,Contact Owner\r\n2022-06-24,1,10000,270,1 out of 2,Carpet Area,Jadavpur University,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-29,2,7200,630,Ground out of 1,Carpet Area,Birati,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-12,3,12000,1500,Ground out of 2,Carpet Area,Bhadrakali,Kolkata,Furnished,Bachelors,2,Contact Owner\r\n2022-06-26,1,5000,600,2 out of 5,Super Area,Behala,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-04-30,2,8500,700,4 out of 14,Carpet Area,Baruipur,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-27,1,6000,300,Ground out of 3,Super Area,Ballygunge,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-06,2,10000,1300,Ground out of 1,Super Area,Kalikapur,Kolkata,Semi-Furnished,Family,2,Contact Owner\r\n2022-05-20,2,4600,400,3 out of 3,Carpet Area,Behala,Kolkata,Semi-Furnished,Bachelors,1,Contact Owner\r\n2022-07-02,2,12000,650,Ground out of 1,Super Area,"Baishnabghata Patuli Township, Patuli",Kolkata,Unfurnished,Family,2,Contact Owner\r\n2022-05-26,3,30000,2000,Ground out of 2,Super Area,Behala,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-12,3,15000,1068,Ground out of 3,Super Area,Bansdroni,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-06-22,1,7500,150,1 out of 1,Super Area,Salt Lake City,Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-25,1,7500,450,2 out of 2,Carpet Area,New Town,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-07-03,2,5000,800,Ground out of 1,Carpet Area,Baruipur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-04-23,2,15000,1000,Ground out of 2,Super Area,Bansdroni,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-14,2,11000,900,5 out of 5,Super Area,Pancha Sayar,Kolkata,Semi-Furnished,Bachelors,1,Contact Owner\r\n2022-05-27,1,7000,600,Ground out of 2,Carpet Area,Behala,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-19,2,6000,1200,1 out of 1,Super Area,Hooghly-Chinsurah,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-19,2,6000,1200,2 out of 2,Super Area,Hooghly-Chinsurah,Kolkata,Semi-Furnished,Bachelors,2,Contact Owner\r\n2022-07-02,2,7000,650,Ground out of 3,Super Area,"Amtala, Diamond Harbour Road",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-07-06,2,8500,720,4 out of 4,Carpet Area,"Shrachi Village, Madhyam Gram",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-07-02,1,5000,300,1 out of 3,Carpet Area,Kasba,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-06-21,3,30000,1200,Ground out of 2,Carpet Area,VIP Road Haldiram,Kolkata,Unfurnished,Bachelors/Family,3,Contact Agent\r\n2022-06-04,2,10000,700,7 out of 8,Carpet Area,Sarsuna,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-24,3,30000,2000,1 out of 3,Super Area,Naihati,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-14,1,3500,250,Ground out of 4,Super Area,Baksara,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-26,2,8000,1100,Ground out of 3,Carpet Area,Naihati,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-07-02,1,5000,300,Ground out of 2,Carpet Area,Kasba,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-05,2,7500,600,Ground out of 2,Super Area,"Amtala, Diamond Harbour Road",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-18,2,6500,800,Ground out of 2,Carpet Area,"Chak Thakurani, Thakurpukur",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-07,1,7500,680,1 out of 3,Super Area,Jadavpur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-07,1,7500,680,Ground out of 2,Super Area,Jadavpur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-26,2,16000,850,1 out of 4,Carpet Area,Salt Lake City Sector 1,Kolkata,Semi-Furnished,Bachelors,1,Contact Agent\r\n2022-06-26,2,16000,850,1 out of 2,Carpet Area,Salt Lake City Sector 1,Kolkata,Semi-Furnished,Bachelors,1,Contact Agent\r\n2022-05-30,2,6500,700,Ground out of 2,Super Area,Bandel,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-05-22,3,40000,1500,Ground out of 2,Super Area,Beliaghata,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-18,2,12500,950,1 out of 4,Super Area,"Magnolia Prestige, Rajarhat",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-06-08,2,5500,500,Ground out of 2,Super Area,"Baishnabghata Patuli Township, Patuli",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-25,1,5000,450,2 out of 4,Carpet Area,"Dum Dum Heights, Jessore Road",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-03,2,6500,700,Ground out of 2,Super Area,Sonarpur,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-05-12,1,8000,500,1 out of 2,Super Area,Lake Town,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-01,3,14500,1800,Ground out of 2,Super Area,Belghoria,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-23,1,8200,500,1 out of 3,Carpet Area,"Rabindra Pally, Keshtopur",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-23,2,15000,480,Ground out of 3,Carpet Area,shukhobrishti,Kolkata,Furnished,Bachelors/Family,2,Contact Owner\r\n2022-06-21,6,20000,1000,1 out of 1,Super Area,Sonarpur,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-06-22,2,6700,800,1 out of 2,Super Area,"Baishnavghata patuli , house number s-300 Kolkata 700094",Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-27,1,10000,435,2 out of 3,Super Area,Kasba,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-07,2,7000,700,Ground out of 2,Carpet Area,Dum Dum Metro,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent\r\n2022-06-25,2,22000,800,4 out of 4,Super Area,"Hazra, Kalighat",Kolkata,Furnished,Bachelors/Family,1,Contact Agent\r\n2022-06-27,2,6500,450,1 out of 3,Super Area,Ajoy Nagar,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-31,2,8500,550,2 out of 3,Carpet Area,Kasba -East,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Agent\r\n2022-06-03,2,18000,800,Ground out of 4,Carpet Area,Salt Lake City,Kolkata,Unfurnished,Bachelors,2,Contact Agent\r\n2022-06-27,2,12000,550,Ground out of 2,Carpet Area,Baghajatin,Kolkata,Semi-Furnished,Family,2,Contact Owner\r\n2022-05-15,1,9000,600,2 out of 4,Super Area,Behala,Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-09,1,6000,500,Ground out of 1,Super Area,"New Garia, Garia",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-04-28,2,20000,1000,1 out of 2,Super Area,Anandapur,Kolkata,Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-23,1,5000,300,1 out of 2,Carpet Area,Dum Dum Metro,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-28,2,12000,1200,1 out of 3,Super Area,Boral,Kolkata,Furnished,Bachelors/Family,2,Contact Owner\r\n2022-06-23,2,10000,500,3 out of 4,Carpet Area,"Rabindra Pally, Keshtopur",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-04-29,4,18000,1200,1 out of 2,Super Area,Bagbazar,Kolkata,Unfurnished,Family,2,Contact Owner\r\n2022-06-13,2,15000,900,1 out of 2,Carpet Area,Salt Lake City Sector 1,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent\r\n2022-06-13,3,22000,1300,Ground out of 2,Carpet Area,Salt Lake City Sector 2,Kolkata,Unfurnished,Bachelors/Family,3,Contact Agent\r\n2022-06-13,4,35000,1600,1 out of 5,Carpet Area,Salt Lake City Sector 3,Kolkata,Unfurnished,Bachelors/Family,3,Contact Agent\r\n2022-05-14,3,21000,1450,Ground out of 1,Super Area,Ajoy Nagar,Kolkata,Unfurnished,Family,2,Contact Owner\r\n2022-07-06,2,25000,1100,2 out of 2,Super Area,"Action Area 1, Rajarhat Newtown",Kolkata,Furnished,Bachelors,2,Contact Agent\r\n2022-06-16,2,180000,950,Ground out of 1,Carpet Area,"Avenue S, Santoshpur",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-06,1,6000,600,8 out of 5,Carpet Area,Pratiraksha Nagar,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-07-04,2,14000,700,Ground out of 2,Carpet Area,"Kudghat, Ashok Nagar",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-15,3,8000,750,Ground out of 2,Super Area,"Sakher Bazar, Purba Barisha",Kolkata,Unfurnished,Family,1,Contact Owner\r\n2022-05-04,2,8000,1000,Ground out of 1,Super Area,"Purbasan, Thakurpukur",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-04-25,1,6000,220,Ground out of 2,Super Area,"Bidhan Pally, Bansdroni",Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-21,1,8000,300,1 out of 3,Carpet Area,"Naktala, Garia",Kolkata,Semi-Furnished,Bachelors,1,Contact Agent\r\n2022-06-27,1,6000,300,Ground out of 1,Carpet Area,Tiljala Road,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent\r\n2022-07-02,1,20000,700,1 out of 2,Super Area,Sankaritola,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-07-06,3,12000,800,Ground out of 1,Super Area,"Parnashree Lake, Behala",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-04-28,3,15000,1600,1 out of 3,Super Area,Garia,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-15,2,14000,1000,1 out of 3,Carpet Area,Kasba,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-30,1,5000,20,2 out of 3,Super Area,Dakshineswar,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-10,2,7000,400,Ground out of 2,Carpet Area,chatana,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-23,1,3900,200,2 out of 2,Super Area,Shyam Bazar,Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-09,3,14000,840,1 out of 4,Carpet Area,Mukundapur,Kolkata,Unfurnished,Bachelors,2,Contact Owner\r\n2022-06-19,1,6300,300,1 out of 1,Carpet Area,Salt Lake City Sector 5,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent\r\n2022-07-03,2,13000,550,1 out of 2,Carpet Area,Salt Lake City Sector 5,Kolkata,Furnished,Bachelors/Family,2,Contact Agent\r\n2022-07-03,1,6800,300,1 out of 2,Carpet Area,Salt Lake City Sector 5,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent\r\n2022-05-14,2,8000,800,1 out of 1,Super Area,Behala Chowrasta,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-10,2,10000,740,Ground out of 6,Carpet Area,Sonarpur,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-04-25,2,18000,1300,1 out of 1,Super Area,Santoshpur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-13,2,8000,650,Ground out of 1,Super Area,"Garia Station, Garia",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-06,2,8000,490,1 out of 1,Super Area,Entally,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-08,1,4700,250,2 out of 2,Super Area,Kaikhali,Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-08,1,4700,250,Ground out of 1,Super Area,"Dash Drone, Rajarhat Newtown",Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-06,1,4500,450,1 out of 2,Super Area,"Rabindra Pally, Keshtopur",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-30,1,6000,300,Ground out of 1,Carpet Area,Salt Lake City Sector 1,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-24,2,16000,750,1 out of 3,Super Area,"Rajdanga Gardens, Kasba",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-07-01,1,4700,250,1 out of 2,Super Area,Kaikhali,Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-17,2,14000,751,3 out of 3,Carpet Area,Baghajatin,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-06-26,2,9000,900,Ground out of 2,Carpet Area,Lake Town,Kolkata,Semi-Furnished,Bachelors,1,Contact Owner\r\n2022-06-23,2,5000,400,1 out of 3,Carpet Area,Keshtopur,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-13,2,17500,1000,Ground out of 2,Carpet Area,Salt Lake City,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Agent\r\n2022-06-11,2,8500,1000,Ground out of 1,Carpet Area,South Baksara,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-26,3,15000,1500,1 out of 1,Carpet Area,"Chandannagar, Hooghly-Chinsurah",Kolkata,Semi-Furnished,Family,2,Contact Owner\r\n2022-04-25,2,12500,750,1 out of 3,Carpet Area,"Sukhpally, Haltu",Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-11,1,13000,1200,2 out of 4,Super Area,Kasba,Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-06,2,8000,700,Ground out of 1,Super Area,"Sakher Bazar, Purba Barisha",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-05-10,2,8000,700,4 out of 4,Carpet Area,Garia Dhalua Nabapally,Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-21,2,8000,1000,Ground out of 2,Super Area,"Chinar Park, Rajarhat",Kolkata,Semi-Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-12,2,7000,1200,1 out of 3,Super Area,Konnagar,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-05,2,2200,550,2 out of 3,Super Area,Behala silpara,Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-06-25,2,8000,800,Ground out of 4,Carpet Area,Vip Road,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-06-11,2,5500,280,1 out of 3,Super Area,New Barrakpur,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-07-04,3,20000,1100,Ground out of 2,Super Area,"Thakurpukur, Kolkata",Kolkata,Unfurnished,Bachelors/Family,3,Contact Owner\r\n2022-05-10,2,7000,950,Ground out of 2,Super Area,Kaikhali,Kolkata,Unfurnished,Bachelors/Family,1,Contact Agent\r\n2022-05-13,1,3500,250,1 out of 2,Super Area,"Phool Bagan, Kankurgachi",Kolkata,Furnished,Bachelors/Family,1,Contact Owner\r\n2022-05-10,2,5000,1000,Ground out of 2,Carpet Area,Hindmotor,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-06-30,3,20000,1000,Ground out of 2,Carpet Area,Salt Lake City Sector 1,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-27,2,7000,650,Ground out of 2,Super Area,Howrah,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-08,2,10000,700,1 out of 2,Super Area,Benia Pukur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-05-15,2,7000,700,Ground out of 3,Carpet Area,Baguiati,Kolkata,Unfurnished,Bachelors,1,Contact Owner\r\n2022-06-29,3,12000,1000,Ground out of 3,Super Area,E M Bypass,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-13,2,14500,900,1 out of 4,Carpet Area,"Panchanan Tola, Thakurpukur",Kolkata,Unfurnished,Bachelors,2,Contact Owner\r\n2022-05-25,1,6000,700,1 out of 2,Super Area,"VIP Nagar, E M Bypass",Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-07-04,2,9500,700,1 out of 2,Super Area,Jadavpur,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-27,2,10000,450,2 out of 1,Carpet Area,Behala,Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-05-06,1,3500,120,Ground out of 3,Super Area,Dum Dum Cantonment,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-01,2,9000,800,1 out of 2,Super Area,"New Garia, Garia",Kolkata,Semi-Furnished,Bachelors/Family,2,Contact Owner\r\n2022-06-07,3,40000,1220,2 out of 3,Carpet Area,Salt Lake City Sector 3,Kolkata,Unfurnished,Bachelors/Family,2,Contact Owner\r\n2022-06-23,3,16500,1100,Ground out of 3,Super Area,Mominpur,Kolkata,Unfurnished,Bachelors/Family,1,Contact Owner\r\n2022-06-12,3,8000,700,Ground out of 3,Carpet Area,"Halisahar Station Road, Kanchrapara",Kolkata,Unfurnished,Family,2,Contact Owner\r\n2022-05-10,2,12000,800,Ground out of 3,Super Area,Santoshpur,Kolkata,Furnished,

# **House Rent Prediction**

The rent of a housing property depends on a lot of factors like:

number of bedrooms, hall, and kitchen
size of the property
the floor of the house
area type
area locality
City
furnishing status of the house

###I will start the task of house rent prediction by importing the necessary Python libraries and the dataset:

In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import plotly.express as px
import plotly.graph_objects as go

In [3]:
data = pd.read_csv("House_Rent_Dataset.csv")
print(data.head())

    Posted On  BHK   Rent  Size            Floor    Area Type  \
0  2022-05-18    2  10000  1100  Ground out of 2   Super Area
1  2022-05-13    2  20000   800       1 out of 3   Super Area
2  2022-05-16    2  17000  1000       1 out of 3   Super Area
3  2022-07-04    2  10000   800       1 out of 2   Super Area
4  2022-05-09    2   7500   850       1 out of 2  Carpet Area

              Area Locality     City Furnishing Status  Tenant Preferred  \
0                    Bandel  Kolkata       Unfurnished  Bachelors/Family
1  Phool Bagan, Kankurgachi  Kolkata    Semi-Furnished  Bachelors/Family
2   Salt Lake City Sector 2  Kolkata    Semi-Furnished  Bachelors/Family
3               Dumdum Park  Kolkata       Unfurnished  Bachelors/Family
4             South Dum Dum  Kolkata       Unfurnished         Bachelors

   Bathroom Point of Contact
0         2    Contact Owner
1         1    Contact Owner
2         1    Contact Owner
3         1    Contact Owner
4         1    Contact Owner

Before moving forward, let’s check if the data contains null values or not:

In [4]:
data.isna().sum()

Posted On            0
BHK                  0
Rent                 0
Size                 0
Floor                0
Area Type            0
Area Locality        0
City                 0
Furnishing Status    0
Tenant Preferred     0
Bathroom             0
Point of Contact     0
dtype: int64

Let’s have a look at the descriptive statistics of the data:

In [5]:
data.describe()

               BHK          Rent         Size     Bathroom
count  4746.000000  4.746000e+03  4746.000000  4746.000000
mean      2.083860  3.499345e+04   967.490729     1.965866
std       0.832256  7.810641e+04   634.202328     0.884532
min       1.000000  1.200000e+03    10.000000     1.000000
25%       2.000000  1.000000e+04   550.000000     1.000000
50%       2.000000  1.600000e+04   850.000000     2.000000
75%       3.000000  3.300000e+04  1200.000000     2.000000
max       6.000000  3.500000e+06  8000.000000    10.000000

Now let’s have a look at the mean, median, highest, and lowest rent of the houses:

In [9]:
data['Rent'].mean()

np.float64(34993.45132743363)

In [10]:
data["Rent"].median()

16000.0

In [11]:
data['Rent'].max()

3500000

In [12]:
data['Rent'].min()

1200

Now let’s have a look at the rent of the houses in different cities according to the number of bedrooms, halls, and kitchens:

In [13]:
figure = px.bar(data,x=data['City'],
                y=data['Rent'],
                color=data["BHK"],
                title="Rent in Different Cities According to BHK")
figure.show()

Now let’s have a look at the rent of the houses in different cities according to the area type:

In [14]:
figure = px.bar(data, x=data["City"],
                y = data["Rent"],
                color = data["Area Type"],
            title="Rent in Different Cities According to Area Type")
figure.show()

Now let’s have a look at the rent of the houses in different cities according to the furnishing status of the house:

In [15]:
figure = px.bar(data, x=data["City"],
                y = data["Rent"],
                color = data['Furnishing Status'],
            title="Rent in Different Cities According to Furnishing Status")
figure.show()

Now let’s have a look at the rent of the houses in different cities according to the size of the house:

In [18]:
figure = px.bar(data, x=data["City"],
                y = data["Rent"],
                color = data["Size"],
            title="Rent in Different Cities According to Size")
figure.show()

Now let’s have a look at the number of houses available for rent in different cities according to the dataset:

In [19]:
cities = data['City'].value_counts()
cities

City
Mumbai       972
Chennai      891
Bangalore    886
Hyderabad    868
Delhi        605
Kolkata      524
Name: count, dtype: int64

In [23]:
label = cities.index
label

Index(['Mumbai', 'Chennai', 'Bangalore', 'Hyderabad', 'Delhi', 'Kolkata'], dtype='object', name='City')

In [25]:
counts = cities.values
counts

array([972, 891, 886, 868, 605, 524])

In [26]:
colors = ["gold","lightgreen"]
colors

['gold', 'lightgreen']

In [34]:
fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.4)])
fig.update_layout(title_text='Number of Houses Available for Rent')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=colors, line=dict(color='black', width=3)))
fig.show()

Now let’s have a look at the number of houses available for different types of tenants:

In [37]:
# Preference of Tenant
tenant = data["Tenant Preferred"].value_counts()
label = tenant.index
counts = tenant.values
colors = ['gold','lightgreen']

In [38]:
tenant

Tenant Preferred
Bachelors/Family    3444
Bachelors            830
Family               472
Name: count, dtype: int64

In [39]:
label

Index(['Bachelors/Family', 'Bachelors', 'Family'], dtype='object', name='Tenant Preferred')

In [40]:
counts

array([3444,  830,  472])

In [41]:
fig = go.Figure(data=[go.Pie(labels=label, values=counts, hole=0.4)])
fig.update_layout(title_text='Number of Houses Available for Different Types Of Tenants')
fig.update_traces(hoverinfo='label+percent', textinfo='value', textfont_size=30,
                  marker=dict(colors=colors, line=dict(color='black', width=3)))
fig.show()

# House Rent Prediction Model

Now I will convert all the categorical features into numerical features that we need to train a house rent prediction model:

In [42]:
data["Area Type"] = data["Area Type"].map({"Super Area": 1,
                                           "Carpet Area": 2,
                                           "Built Area": 3})
data["City"] = data["City"].map({"Mumbai": 4000, "Chennai": 6000,
                                 "Bangalore": 5600, "Hyderabad": 5000,
                                 "Delhi": 1100, "Kolkata": 7000})
data["Furnishing Status"] = data["Furnishing Status"].map({"Unfurnished": 0,
                                                           "Semi-Furnished": 1,
                                                           "Furnished": 2})
data["Tenant Preferred"] = data["Tenant Preferred"].map({"Bachelors/Family": 2,
                                                         "Bachelors": 1,
                                                         "Family": 3})
data.head()

,Posted On,BHK,Rent,Size,Floor,Area Type,Area Locality,City,Furnishing Status,Tenant Preferred,Bathroom,Point of Contact
0,2022-05-18,2,10000,1100,Ground out of 2,1,Bandel,7000,0,2,2,Contact Owner
1,2022-05-13,2,20000,800,1 out of 3,1,"Phool Bagan, Kankurgachi",7000,1,2,1,Contact Owner
2,2022-05-16,2,17000,1000,1 out of 3,1,Salt Lake City Sector 2,7000,1,2,1,Contact Owner
3,2022-07-04,2,10000,800,1 out of 2,1,Dumdum Park,7000,0,2,1,Contact Owner
4,2022-05-09,2,7500,850,1 out of 2,2,South Dum Dum,7000,0,1,1,Contact Owner

Now I will split the data into training and test sets:

In [43]:
#splitting data
from sklearn.model_selection import train_test_split

x = np.array(data[["BHK", "Size", "Area Type", "City",
                   "Furnishing Status", "Tenant Preferred",
                   "Bathroom"]])
y = np.array(data[["Rent"]])

xtrain, xtest, ytrain, ytest = train_test_split(x, y,
                                                test_size=0.10,
                                                random_state=42)

Now let’s train a house rent prediction model using an LSTM neural network model:

In [44]:
from keras.models import Sequential
from keras.layers import Dense, LSTM

model = Sequential()
model.add(LSTM(128, return_sequences=True,
               input_shape= (xtrain.shape[1], 1)))
model.add(LSTM(64, return_sequences=False))
model.add(Dense(25))
model.add(Dense(1))
model.summary()

/usr/local/lib/python3.12/dist-packages/keras/src/layers/rnn/rnn.py:199: UserWarning:

Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ lstm (LSTM)                     │ (None, 7, 128)         │        66,560 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ lstm_1 (LSTM)                   │ (None, 64)             │        49,408 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense (Dense)                   │ (None, 25)             │         1,625 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_1 (Dense)                 │ (None, 1)              │            26 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 117,619 (459.45 KB)

 Trainable params: 117,619 (459.45 KB)

 Non-trainable params: 0 (0.00 B)

In [45]:
model.compile(optimizer='adam', loss='mean_squared_error')
model.fit(xtrain, ytrain, batch_size=1, epochs=21)

Epoch 1/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 27s 5ms/step - loss: 4498895872.0000
Epoch 2/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 11901833216.0000
Epoch 3/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 4438604288.0000
Epoch 4/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 44s 6ms/step - loss: 6301153280.0000
Epoch 5/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 26s 6ms/step - loss: 3378171136.0000
Epoch 6/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 5214342144.0000
Epoch 7/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 4973003264.0000
Epoch 8/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 25s 6ms/step - loss: 14261158912.0000
Epoch 9/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 4386351104.0000
Epoch 10/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 3813910016.0000
Epoch 11/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 2166669568.0000
Epoch 12/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 3066020608.0000
Epoch 13/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 6152150528.0000
Epoch 14/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 3645329664.0000
Epoch 15/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 2563413760.0000
Epoch 16/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 5150848512.0000
Epoch 17/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 1870912768.0000
Epoch 18/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 22s 5ms/step - loss: 2554413056.0000
Epoch 19/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 24s 6ms/step - loss: 10839076864.0000
Epoch 20/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 2156093952.0000
Epoch 21/21
4271/4271 ━━━━━━━━━━━━━━━━━━━━ 23s 5ms/step - loss: 7738042368.0000

Now here’s how to predict the rent of a housing property using the trained model:

In [46]:
print("Enter House Details to Predict Rent")
a = int(input("Number of BHK: "))
b = int(input("Size of the House: "))
c = int(input("Area Type (Super Area = 1, Carpet Area = 2, Built Area = 3): "))
d = int(input("Pin Code of the City: "))
e = int(input("Furnishing Status of the House (Unfurnished = 0, Semi-Furnished = 1, Furnished = 2): "))
f = int(input("Tenant Type (Bachelors = 1, Bachelors/Family = 2, Only Family = 3): "))
g = int(input("Number of bathrooms: "))
features = np.array([[a, b, c, d, e, f, g]])
print("Predicted House Price = ", model.predict(features))

Enter House Details to Predict Rent
Number of BHK: 2
Size of the House: 1500
Area Type (Super Area = 1, Carpet Area = 2, Built Area = 3): 2
Pin Code of the City: 7000
Furnishing Status of the House (Unfurnished = 0, Semi-Furnished = 1, Furnished = 2): 1
Tenant Type (Bachelors = 1, Bachelors/Family = 2, Only Family = 3): 2
Number of bathrooms: 2
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 157ms/step
Predicted House Price =  [[32116.404]]

In [48]:
print("Enter House Details to Predict Rent")
a = int(input("Number of BHK: "))
b = int(input("Size of the House: "))
c = int(input("Area Type (Super Area = 1, Carpet Area = 2, Built Area = 3): "))
d = int(input("Pin Code of the City: "))
e = int(input("Furnishing Status of the House (Unfurnished = 0, Semi-Furnished = 1, Furnished = 2): "))
f = int(input("Tenant Type (Bachelors = 1, Bachelors/Family = 2, Only Family = 3): "))
g = int(input("Number of bathrooms: "))
features = np.array([[a, b, c, d, e, f, g]])
print("Predicted House Price = ", model.predict(features))

Enter House Details to Predict Rent
Number of BHK: 3
Size of the House: 2000
Area Type (Super Area = 1, Carpet Area = 2, Built Area = 3): 1
Pin Code of the City: 1100
Furnishing Status of the House (Unfurnished = 0, Semi-Furnished = 1, Furnished = 2): 2
Tenant Type (Bachelors = 1, Bachelors/Family = 2, Only Family = 3): 3
Number of bathrooms: 3
1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 30ms/step
Predicted House Price =  [[47857.61]]

# **Summary**

So this is how to use Machine Learning to predict the rent of a housing property. With appropriate data and Machine Learning techniques, many real estate platforms find the housing options according to the customer’s budget. I hope you liked this article on predicting house rent with Machine Learning using Python.